# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `google-api-client` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module Google
end

module Google::Apis
  class << self
    def default_logger; end
    def logger; end
    def logger=(_arg0); end
    def rails_logger; end
  end
end

class Google::Apis::AuthorizationError < ::Google::Apis::Error
end

class Google::Apis::BatchError < ::Google::Apis::Error
end

class Google::Apis::ClientError < ::Google::Apis::Error
end

class Google::Apis::ClientOptions < ::Struct
  def application_name; end
  def application_name=(_); end
  def application_version; end
  def application_version=(_); end
  def log_http_requests; end
  def log_http_requests=(_); end
  def open_timeout_sec; end
  def open_timeout_sec=(_); end
  def proxy_url; end
  def proxy_url=(_); end
  def read_timeout_sec; end
  def read_timeout_sec=(_); end
  def send_timeout_sec; end
  def send_timeout_sec=(_); end
  def transparent_gzip_decompression; end
  def transparent_gzip_decompression=(_); end

  class << self
    def [](*_arg0); end
    def default; end
    def inspect; end
    def members; end
    def new(*_arg0); end
  end
end

module Google::Apis::Core
end

class Google::Apis::Core::ApiCommand < ::Google::Apis::Core::HttpCommand
  def allow_form_encoding?; end
  def check_status(status, header = T.unsafe(nil), body = T.unsafe(nil), message = T.unsafe(nil)); end
  def decode_response_body(content_type, body); end
  def prepare!; end
  def request_object; end
  def request_object=(_arg0); end
  def request_representation; end
  def request_representation=(_arg0); end
  def response_class; end
  def response_class=(_arg0); end
  def response_representation; end
  def response_representation=(_arg0); end

  private

  def extract_v1_error_details(error); end
  def extract_v2_error_details(error); end
  def normalize_fields_param(fields); end
  def parse_error(body); end
end

Google::Apis::Core::ApiCommand::ERROR_REASON_MAPPING = T.let(T.unsafe(nil), Hash)

Google::Apis::Core::ApiCommand::FIELDS_PARAM = T.let(T.unsafe(nil), String)

Google::Apis::Core::ApiCommand::JSON_CONTENT_TYPE = T.let(T.unsafe(nil), String)

class Google::Apis::Core::BaseService
  include(::Google::Apis::Core::Logging)

  def initialize(root_url, base_path); end

  def authorization; end
  def authorization=(authorization); end
  def base_path; end
  def base_path=(_arg0); end
  def batch(options = T.unsafe(nil)); end
  def batch_path; end
  def batch_path=(_arg0); end
  def batch_upload(options = T.unsafe(nil)); end
  def client; end
  def client=(_arg0); end
  def client_options; end
  def client_options=(_arg0); end
  def fetch_all(max: T.unsafe(nil), items: T.unsafe(nil), cache: T.unsafe(nil), response_page_token: T.unsafe(nil), &block); end
  def http(method, url, params: T.unsafe(nil), body: T.unsafe(nil), download_dest: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def request_options; end
  def request_options=(_arg0); end
  def root_url; end
  def root_url=(_arg0); end
  def upload_path; end
  def upload_path=(_arg0); end

  protected

  def apply_command_defaults(_command); end
  def execute_or_queue_command(command, &callback); end
  def make_download_command(method, path, options); end
  def make_simple_command(method, path, options); end
  def make_upload_command(method, path, options); end

  private

  def batch?; end
  def current_batch; end
  def end_batch; end
  def new_client; end
  def start_batch(cmd); end
  def user_agent; end
end

class Google::Apis::Core::BaseUploadCommand < ::Google::Apis::Core::ApiCommand
  def prepare!; end
  def release!; end
  def upload_content_type; end
  def upload_content_type=(_arg0); end
  def upload_io; end
  def upload_io=(_arg0); end
  def upload_source; end
  def upload_source=(_arg0); end

  private

  def streamable?(upload_source); end
end

Google::Apis::Core::BaseUploadCommand::CONTENT_TYPE_HEADER = T.let(T.unsafe(nil), String)

Google::Apis::Core::BaseUploadCommand::UPLOAD_CONTENT_LENGTH = T.let(T.unsafe(nil), String)

Google::Apis::Core::BaseUploadCommand::UPLOAD_CONTENT_TYPE_HEADER = T.let(T.unsafe(nil), String)

Google::Apis::Core::BaseUploadCommand::UPLOAD_PROTOCOL_HEADER = T.let(T.unsafe(nil), String)

class Google::Apis::Core::BatchCommand < ::Google::Apis::Core::HttpCommand
  def initialize(method, url); end

  def add(call, &block); end

  protected

  def decode_response_body(content_type, body); end
  def ensure_valid_command(command); end
  def header_to_id(content_id); end
  def id_to_header(call_id); end
  def prepare!; end
  def split_parts(body, boundary); end
end

Google::Apis::Core::BatchCommand::MULTIPART_MIXED = T.let(T.unsafe(nil), String)

class Google::Apis::Core::BatchUploadCommand < ::Google::Apis::Core::BatchCommand
  def ensure_valid_command(command); end
  def prepare!; end
end

class Google::Apis::Core::CallDeserializer
  def to_http_response(call_response); end

  protected

  def split_header_and_body(response); end
end

class Google::Apis::Core::CallSerializer
  def to_part(call); end

  protected

  def build_body(call); end
  def build_head(call); end
end

class Google::Apis::Core::CompositeIO
  def initialize(*ios); end

  def length; end
  def pos; end
  def pos=(pos); end
  def read(length = T.unsafe(nil), buf = T.unsafe(nil)); end
  def rewind; end
  def size; end
end

class Google::Apis::Core::DownloadCommand < ::Google::Apis::Core::ApiCommand
  def download_dest; end
  def download_dest=(_arg0); end
  def execute_once(client, &block); end
  def prepare!; end
  def release!; end
end

Google::Apis::Core::DownloadCommand::OK_STATUS = T.let(T.unsafe(nil), Array)

Google::Apis::Core::DownloadCommand::RANGE_HEADER = T.let(T.unsafe(nil), String)

class Google::Apis::Core::FilePart
  def initialize(io, header = T.unsafe(nil)); end

  def to_io(boundary); end
end

module Google::Apis::Core::Hashable
  def to_h; end

  class << self
    def process_value(val); end
  end
end

class Google::Apis::Core::HttpCommand
  include(::Google::Apis::Core::Logging)

  def initialize(method, url, body: T.unsafe(nil)); end

  def allow_form_encoding?; end
  def apply_request_options(req_header); end
  def authorization_refreshable?; end
  def body; end
  def body=(_arg0); end
  def check_status(status, header = T.unsafe(nil), body = T.unsafe(nil), message = T.unsafe(nil)); end
  def connection; end
  def connection=(_arg0); end
  def decode_response_body(_content_type, body); end
  def error(err, rethrow: T.unsafe(nil), &block); end
  def execute(client); end
  def execute_once(client); end
  def header; end
  def header=(_arg0); end
  def method; end
  def method=(_arg0); end
  def options; end
  def options=(_arg0); end
  def params; end
  def params=(_arg0); end
  def prepare!; end
  def process_response(status, header, body); end
  def query; end
  def query=(_arg0); end
  def refresh_authorization; end
  def release!; end
  def success(result, &block); end
  def url; end
  def url=(_arg0); end

  private

  def form_encoded?; end
  def normalize_query_value(v); end
end

Google::Apis::Core::HttpCommand::RETRIABLE_ERRORS = T.let(T.unsafe(nil), Array)

module Google::Apis::Core::JsonObjectSupport
  mixes_in_class_methods(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def to_json(*a); end

  class << self
    def included(base); end
  end
end

module Google::Apis::Core::JsonObjectSupport::ClassMethods
  def from_json(json); end
end

class Google::Apis::Core::JsonPart
  def initialize(value, header = T.unsafe(nil)); end

  def to_io(boundary); end
end

class Google::Apis::Core::JsonRepresentation < ::Representable::Decorator
  include(::Representable::Hash)
  include(::Representable::JSON)
  include(::Google::Apis::Core::JsonRepresentationSupport)
  extend(::Representable::JSON::ClassMethods)
  extend(::Google::Apis::Core::JsonRepresentationSupport::JsonSupport)
end

module Google::Apis::Core::JsonRepresentationSupport
  mixes_in_class_methods(::Google::Apis::Core::JsonRepresentationSupport::JsonSupport)

  class << self
    def included(base); end
  end
end

module Google::Apis::Core::JsonRepresentationSupport::JsonSupport
  def collection(name, options = T.unsafe(nil)); end
  def getter_fn(name); end
  def hash(name = T.unsafe(nil), options = T.unsafe(nil)); end
  def if_fn(name); end
  def property(name, options = T.unsafe(nil)); end
  def set_default_options(name, options); end
end

module Google::Apis::Core::Logging
  def logger; end
end

class Google::Apis::Core::Multipart
  def initialize(content_type: T.unsafe(nil), boundary: T.unsafe(nil)); end

  def add_json(body, content_id: T.unsafe(nil)); end
  def add_upload(upload_io, content_type: T.unsafe(nil), content_id: T.unsafe(nil)); end
  def assemble; end
  def content_type; end
end

Google::Apis::Core::Multipart::MULTIPART_RELATED = T.let(T.unsafe(nil), String)

class Google::Apis::Core::MultipartUploadCommand < ::Google::Apis::Core::BaseUploadCommand
  def prepare!; end
end

Google::Apis::Core::MultipartUploadCommand::MULTIPART_PROTOCOL = T.let(T.unsafe(nil), String)

Google::Apis::Core::MultipartUploadCommand::MULTIPART_RELATED = T.let(T.unsafe(nil), String)

class Google::Apis::Core::PagedResults
  include(::Enumerable)

  def initialize(service, max: T.unsafe(nil), items: T.unsafe(nil), cache: T.unsafe(nil), response_page_token: T.unsafe(nil), &block); end

  def each; end
  def last_result; end
end

class Google::Apis::Core::RawUploadCommand < ::Google::Apis::Core::BaseUploadCommand
  def prepare!; end
end

Google::Apis::Core::RawUploadCommand::RAW_PROTOCOL = T.let(T.unsafe(nil), String)

class Google::Apis::Core::ResumableUploadCommand < ::Google::Apis::Core::BaseUploadCommand
  def execute_once(client, &block); end
  def prepare!; end
  def process_response(status, header, body); end
  def send_query_command(client); end
  def send_start_command(client); end
  def send_upload_command(client); end
end

Google::Apis::Core::ResumableUploadCommand::BYTES_RECEIVED_HEADER = T.let(T.unsafe(nil), String)

Google::Apis::Core::ResumableUploadCommand::QUERY_COMMAND = T.let(T.unsafe(nil), String)

Google::Apis::Core::ResumableUploadCommand::RESUMABLE = T.let(T.unsafe(nil), String)

Google::Apis::Core::ResumableUploadCommand::START_COMMAND = T.let(T.unsafe(nil), String)

Google::Apis::Core::ResumableUploadCommand::STATUS_ACTIVE = T.let(T.unsafe(nil), String)

Google::Apis::Core::ResumableUploadCommand::STATUS_CANCELLED = T.let(T.unsafe(nil), String)

Google::Apis::Core::ResumableUploadCommand::STATUS_FINAL = T.let(T.unsafe(nil), String)

Google::Apis::Core::ResumableUploadCommand::UPLOAD_COMMAND = T.let(T.unsafe(nil), String)

Google::Apis::Core::ResumableUploadCommand::UPLOAD_COMMAND_HEADER = T.let(T.unsafe(nil), String)

Google::Apis::Core::ResumableUploadCommand::UPLOAD_OFFSET_HEADER = T.let(T.unsafe(nil), String)

Google::Apis::Core::ResumableUploadCommand::UPLOAD_STATUS_HEADER = T.let(T.unsafe(nil), String)

Google::Apis::Core::ResumableUploadCommand::UPLOAD_URL_HEADER = T.let(T.unsafe(nil), String)

module Google::Apis::DriveV3
end

Google::Apis::DriveV3::AUTH_DRIVE = T.let(T.unsafe(nil), String)

Google::Apis::DriveV3::AUTH_DRIVE_APPDATA = T.let(T.unsafe(nil), String)

Google::Apis::DriveV3::AUTH_DRIVE_FILE = T.let(T.unsafe(nil), String)

Google::Apis::DriveV3::AUTH_DRIVE_METADATA = T.let(T.unsafe(nil), String)

Google::Apis::DriveV3::AUTH_DRIVE_METADATA_READONLY = T.let(T.unsafe(nil), String)

Google::Apis::DriveV3::AUTH_DRIVE_PHOTOS_READONLY = T.let(T.unsafe(nil), String)

Google::Apis::DriveV3::AUTH_DRIVE_READONLY = T.let(T.unsafe(nil), String)

Google::Apis::DriveV3::AUTH_DRIVE_SCRIPTS = T.let(T.unsafe(nil), String)

class Google::Apis::DriveV3::About
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def app_installed; end
  def app_installed=(_arg0); end
  def app_installed?; end
  def can_create_team_drives; end
  def can_create_team_drives=(_arg0); end
  def can_create_team_drives?; end
  def export_formats; end
  def export_formats=(_arg0); end
  def folder_color_palette; end
  def folder_color_palette=(_arg0); end
  def import_formats; end
  def import_formats=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def max_import_sizes; end
  def max_import_sizes=(_arg0); end
  def max_upload_size; end
  def max_upload_size=(_arg0); end
  def storage_quota; end
  def storage_quota=(_arg0); end
  def team_drive_themes; end
  def team_drive_themes=(_arg0); end
  def update!(**args); end
  def user; end
  def user=(_arg0); end
end

class Google::Apis::DriveV3::About::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::About::StorageQuota
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def limit; end
  def limit=(_arg0); end
  def update!(**args); end
  def usage; end
  def usage=(_arg0); end
  def usage_in_drive; end
  def usage_in_drive=(_arg0); end
  def usage_in_drive_trash; end
  def usage_in_drive_trash=(_arg0); end
end

class Google::Apis::DriveV3::About::StorageQuota::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::About::TeamDriveTheme
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def background_image_link; end
  def background_image_link=(_arg0); end
  def color_rgb; end
  def color_rgb=(_arg0); end
  def id; end
  def id=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::About::TeamDriveTheme::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::Change
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def file; end
  def file=(_arg0); end
  def file_id; end
  def file_id=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def removed; end
  def removed=(_arg0); end
  def removed?; end
  def team_drive; end
  def team_drive=(_arg0); end
  def team_drive_id; end
  def team_drive_id=(_arg0); end
  def time; end
  def time=(_arg0); end
  def type; end
  def type=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::Change::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::ChangeList
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def changes; end
  def changes=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def new_start_page_token; end
  def new_start_page_token=(_arg0); end
  def next_page_token; end
  def next_page_token=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::ChangeList::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::Channel
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def address; end
  def address=(_arg0); end
  def expiration; end
  def expiration=(_arg0); end
  def id; end
  def id=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def params; end
  def params=(_arg0); end
  def payload; end
  def payload=(_arg0); end
  def payload?; end
  def resource_id; end
  def resource_id=(_arg0); end
  def resource_uri; end
  def resource_uri=(_arg0); end
  def token; end
  def token=(_arg0); end
  def type; end
  def type=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::Channel::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::Comment
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def anchor; end
  def anchor=(_arg0); end
  def author; end
  def author=(_arg0); end
  def content; end
  def content=(_arg0); end
  def created_time; end
  def created_time=(_arg0); end
  def deleted; end
  def deleted=(_arg0); end
  def deleted?; end
  def html_content; end
  def html_content=(_arg0); end
  def id; end
  def id=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def modified_time; end
  def modified_time=(_arg0); end
  def quoted_file_content; end
  def quoted_file_content=(_arg0); end
  def replies; end
  def replies=(_arg0); end
  def resolved; end
  def resolved=(_arg0); end
  def resolved?; end
  def update!(**args); end
end

class Google::Apis::DriveV3::Comment::QuotedFileContent
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def mime_type; end
  def mime_type=(_arg0); end
  def update!(**args); end
  def value; end
  def value=(_arg0); end
end

class Google::Apis::DriveV3::Comment::QuotedFileContent::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::Comment::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::CommentList
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def comments; end
  def comments=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def next_page_token; end
  def next_page_token=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::CommentList::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::DriveService < ::Google::Apis::Core::BaseService
  def initialize; end

  def copy_file(file_id, file_object = T.unsafe(nil), ignore_default_visibility: T.unsafe(nil), keep_revision_forever: T.unsafe(nil), ocr_language: T.unsafe(nil), supports_team_drives: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def create_comment(file_id, comment_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def create_file(file_object = T.unsafe(nil), ignore_default_visibility: T.unsafe(nil), keep_revision_forever: T.unsafe(nil), ocr_language: T.unsafe(nil), supports_team_drives: T.unsafe(nil), use_content_as_indexable_text: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), upload_source: T.unsafe(nil), content_type: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def create_permission(file_id, permission_object = T.unsafe(nil), email_message: T.unsafe(nil), send_notification_email: T.unsafe(nil), supports_team_drives: T.unsafe(nil), transfer_ownership: T.unsafe(nil), use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def create_reply(file_id, comment_id, reply_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def create_teamdrive(request_id, team_drive_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def delete_comment(file_id, comment_id, fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def delete_file(file_id, supports_team_drives: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def delete_permission(file_id, permission_id, supports_team_drives: T.unsafe(nil), use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def delete_reply(file_id, comment_id, reply_id, fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def delete_revision(file_id, revision_id, fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def delete_teamdrive(team_drive_id, fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def empty_file_trash(fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def export_file(file_id, mime_type, fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), download_dest: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def generate_file_ids(count: T.unsafe(nil), space: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_about(fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_changes_start_page_token(supports_team_drives: T.unsafe(nil), team_drive_id: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_comment(file_id, comment_id, include_deleted: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_file(file_id, acknowledge_abuse: T.unsafe(nil), supports_team_drives: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), download_dest: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_permission(file_id, permission_id, supports_team_drives: T.unsafe(nil), use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_reply(file_id, comment_id, reply_id, include_deleted: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_revision(file_id, revision_id, acknowledge_abuse: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), download_dest: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_teamdrive(team_drive_id, use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def key; end
  def key=(_arg0); end
  def list_changes(page_token, include_corpus_removals: T.unsafe(nil), include_removed: T.unsafe(nil), include_team_drive_items: T.unsafe(nil), page_size: T.unsafe(nil), restrict_to_my_drive: T.unsafe(nil), spaces: T.unsafe(nil), supports_team_drives: T.unsafe(nil), team_drive_id: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def list_comments(file_id, include_deleted: T.unsafe(nil), page_size: T.unsafe(nil), page_token: T.unsafe(nil), start_modified_time: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def list_files(corpora: T.unsafe(nil), corpus: T.unsafe(nil), include_team_drive_items: T.unsafe(nil), order_by: T.unsafe(nil), page_size: T.unsafe(nil), page_token: T.unsafe(nil), q: T.unsafe(nil), spaces: T.unsafe(nil), supports_team_drives: T.unsafe(nil), team_drive_id: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def list_permissions(file_id, page_size: T.unsafe(nil), page_token: T.unsafe(nil), supports_team_drives: T.unsafe(nil), use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def list_replies(file_id, comment_id, include_deleted: T.unsafe(nil), page_size: T.unsafe(nil), page_token: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def list_revisions(file_id, page_size: T.unsafe(nil), page_token: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def list_teamdrives(page_size: T.unsafe(nil), page_token: T.unsafe(nil), q: T.unsafe(nil), use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def quota_user; end
  def quota_user=(_arg0); end
  def stop_channel(channel_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def update_comment(file_id, comment_id, comment_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def update_file(file_id, file_object = T.unsafe(nil), add_parents: T.unsafe(nil), keep_revision_forever: T.unsafe(nil), ocr_language: T.unsafe(nil), remove_parents: T.unsafe(nil), supports_team_drives: T.unsafe(nil), use_content_as_indexable_text: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), upload_source: T.unsafe(nil), content_type: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def update_permission(file_id, permission_id, permission_object = T.unsafe(nil), remove_expiration: T.unsafe(nil), supports_team_drives: T.unsafe(nil), transfer_ownership: T.unsafe(nil), use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def update_reply(file_id, comment_id, reply_id, reply_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def update_revision(file_id, revision_id, revision_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def update_teamdrive(team_drive_id, team_drive_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def user_ip; end
  def user_ip=(_arg0); end
  def watch_change(page_token, channel_object = T.unsafe(nil), include_corpus_removals: T.unsafe(nil), include_removed: T.unsafe(nil), include_team_drive_items: T.unsafe(nil), page_size: T.unsafe(nil), restrict_to_my_drive: T.unsafe(nil), spaces: T.unsafe(nil), supports_team_drives: T.unsafe(nil), team_drive_id: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def watch_file(file_id, channel_object = T.unsafe(nil), acknowledge_abuse: T.unsafe(nil), supports_team_drives: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), download_dest: T.unsafe(nil), options: T.unsafe(nil), &block); end

  protected

  def apply_command_defaults(command); end
end

class Google::Apis::DriveV3::File
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def app_properties; end
  def app_properties=(_arg0); end
  def capabilities; end
  def capabilities=(_arg0); end
  def content_hints; end
  def content_hints=(_arg0); end
  def created_time; end
  def created_time=(_arg0); end
  def description; end
  def description=(_arg0); end
  def explicitly_trashed; end
  def explicitly_trashed=(_arg0); end
  def explicitly_trashed?; end
  def file_extension; end
  def file_extension=(_arg0); end
  def folder_color_rgb; end
  def folder_color_rgb=(_arg0); end
  def full_file_extension; end
  def full_file_extension=(_arg0); end
  def has_augmented_permissions; end
  def has_augmented_permissions=(_arg0); end
  def has_augmented_permissions?; end
  def has_thumbnail; end
  def has_thumbnail=(_arg0); end
  def has_thumbnail?; end
  def head_revision_id; end
  def head_revision_id=(_arg0); end
  def icon_link; end
  def icon_link=(_arg0); end
  def id; end
  def id=(_arg0); end
  def image_media_metadata; end
  def image_media_metadata=(_arg0); end
  def is_app_authorized; end
  def is_app_authorized=(_arg0); end
  def is_app_authorized?; end
  def kind; end
  def kind=(_arg0); end
  def last_modifying_user; end
  def last_modifying_user=(_arg0); end
  def md5_checksum; end
  def md5_checksum=(_arg0); end
  def mime_type; end
  def mime_type=(_arg0); end
  def modified_by_me; end
  def modified_by_me=(_arg0); end
  def modified_by_me?; end
  def modified_by_me_time; end
  def modified_by_me_time=(_arg0); end
  def modified_time; end
  def modified_time=(_arg0); end
  def name; end
  def name=(_arg0); end
  def original_filename; end
  def original_filename=(_arg0); end
  def owned_by_me; end
  def owned_by_me=(_arg0); end
  def owned_by_me?; end
  def owners; end
  def owners=(_arg0); end
  def parents; end
  def parents=(_arg0); end
  def permission_ids; end
  def permission_ids=(_arg0); end
  def permissions; end
  def permissions=(_arg0); end
  def properties; end
  def properties=(_arg0); end
  def quota_bytes_used; end
  def quota_bytes_used=(_arg0); end
  def shared; end
  def shared=(_arg0); end
  def shared?; end
  def shared_with_me_time; end
  def shared_with_me_time=(_arg0); end
  def sharing_user; end
  def sharing_user=(_arg0); end
  def size; end
  def size=(_arg0); end
  def spaces; end
  def spaces=(_arg0); end
  def starred; end
  def starred=(_arg0); end
  def starred?; end
  def team_drive_id; end
  def team_drive_id=(_arg0); end
  def thumbnail_link; end
  def thumbnail_link=(_arg0); end
  def thumbnail_version; end
  def thumbnail_version=(_arg0); end
  def trashed; end
  def trashed=(_arg0); end
  def trashed?; end
  def trashed_time; end
  def trashed_time=(_arg0); end
  def trashing_user; end
  def trashing_user=(_arg0); end
  def update!(**args); end
  def version; end
  def version=(_arg0); end
  def video_media_metadata; end
  def video_media_metadata=(_arg0); end
  def viewed_by_me; end
  def viewed_by_me=(_arg0); end
  def viewed_by_me?; end
  def viewed_by_me_time; end
  def viewed_by_me_time=(_arg0); end
  def viewers_can_copy_content; end
  def viewers_can_copy_content=(_arg0); end
  def viewers_can_copy_content?; end
  def web_content_link; end
  def web_content_link=(_arg0); end
  def web_view_link; end
  def web_view_link=(_arg0); end
  def writers_can_share; end
  def writers_can_share=(_arg0); end
  def writers_can_share?; end
end

class Google::Apis::DriveV3::File::Capabilities
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def can_add_children; end
  def can_add_children=(_arg0); end
  def can_add_children?; end
  def can_change_viewers_can_copy_content; end
  def can_change_viewers_can_copy_content=(_arg0); end
  def can_change_viewers_can_copy_content?; end
  def can_comment; end
  def can_comment=(_arg0); end
  def can_comment?; end
  def can_copy; end
  def can_copy=(_arg0); end
  def can_copy?; end
  def can_delete; end
  def can_delete=(_arg0); end
  def can_delete?; end
  def can_download; end
  def can_download=(_arg0); end
  def can_download?; end
  def can_edit; end
  def can_edit=(_arg0); end
  def can_edit?; end
  def can_list_children; end
  def can_list_children=(_arg0); end
  def can_list_children?; end
  def can_move_item_into_team_drive; end
  def can_move_item_into_team_drive=(_arg0); end
  def can_move_item_into_team_drive?; end
  def can_move_team_drive_item; end
  def can_move_team_drive_item=(_arg0); end
  def can_move_team_drive_item?; end
  def can_read_revisions; end
  def can_read_revisions=(_arg0); end
  def can_read_revisions?; end
  def can_read_team_drive; end
  def can_read_team_drive=(_arg0); end
  def can_read_team_drive?; end
  def can_remove_children; end
  def can_remove_children=(_arg0); end
  def can_remove_children?; end
  def can_rename; end
  def can_rename=(_arg0); end
  def can_rename?; end
  def can_share; end
  def can_share=(_arg0); end
  def can_share?; end
  def can_trash; end
  def can_trash=(_arg0); end
  def can_trash?; end
  def can_untrash; end
  def can_untrash=(_arg0); end
  def can_untrash?; end
  def update!(**args); end
end

class Google::Apis::DriveV3::File::Capabilities::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::File::ContentHints
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def indexable_text; end
  def indexable_text=(_arg0); end
  def thumbnail; end
  def thumbnail=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::File::ContentHints::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::File::ContentHints::Thumbnail
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def image; end
  def image=(_arg0); end
  def mime_type; end
  def mime_type=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::File::ContentHints::Thumbnail::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::File::ImageMediaMetadata
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def aperture; end
  def aperture=(_arg0); end
  def camera_make; end
  def camera_make=(_arg0); end
  def camera_model; end
  def camera_model=(_arg0); end
  def color_space; end
  def color_space=(_arg0); end
  def exposure_bias; end
  def exposure_bias=(_arg0); end
  def exposure_mode; end
  def exposure_mode=(_arg0); end
  def exposure_time; end
  def exposure_time=(_arg0); end
  def flash_used; end
  def flash_used=(_arg0); end
  def flash_used?; end
  def focal_length; end
  def focal_length=(_arg0); end
  def height; end
  def height=(_arg0); end
  def iso_speed; end
  def iso_speed=(_arg0); end
  def lens; end
  def lens=(_arg0); end
  def location; end
  def location=(_arg0); end
  def max_aperture_value; end
  def max_aperture_value=(_arg0); end
  def metering_mode; end
  def metering_mode=(_arg0); end
  def rotation; end
  def rotation=(_arg0); end
  def sensor; end
  def sensor=(_arg0); end
  def subject_distance; end
  def subject_distance=(_arg0); end
  def time; end
  def time=(_arg0); end
  def update!(**args); end
  def white_balance; end
  def white_balance=(_arg0); end
  def width; end
  def width=(_arg0); end
end

class Google::Apis::DriveV3::File::ImageMediaMetadata::Location
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def altitude; end
  def altitude=(_arg0); end
  def latitude; end
  def latitude=(_arg0); end
  def longitude; end
  def longitude=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::File::ImageMediaMetadata::Location::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::File::ImageMediaMetadata::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::File::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::File::VideoMediaMetadata
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def duration_millis; end
  def duration_millis=(_arg0); end
  def height; end
  def height=(_arg0); end
  def update!(**args); end
  def width; end
  def width=(_arg0); end
end

class Google::Apis::DriveV3::File::VideoMediaMetadata::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::FileList
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def files; end
  def files=(_arg0); end
  def incomplete_search; end
  def incomplete_search=(_arg0); end
  def incomplete_search?; end
  def kind; end
  def kind=(_arg0); end
  def next_page_token; end
  def next_page_token=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::FileList::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::GeneratedIds
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def ids; end
  def ids=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def space; end
  def space=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::GeneratedIds::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::Permission
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def allow_file_discovery; end
  def allow_file_discovery=(_arg0); end
  def allow_file_discovery?; end
  def deleted; end
  def deleted=(_arg0); end
  def deleted?; end
  def display_name; end
  def display_name=(_arg0); end
  def domain; end
  def domain=(_arg0); end
  def email_address; end
  def email_address=(_arg0); end
  def expiration_time; end
  def expiration_time=(_arg0); end
  def id; end
  def id=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def photo_link; end
  def photo_link=(_arg0); end
  def role; end
  def role=(_arg0); end
  def team_drive_permission_details; end
  def team_drive_permission_details=(_arg0); end
  def type; end
  def type=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::Permission::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::Permission::TeamDrivePermissionDetail
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def inherited; end
  def inherited=(_arg0); end
  def inherited?; end
  def inherited_from; end
  def inherited_from=(_arg0); end
  def role; end
  def role=(_arg0); end
  def team_drive_permission_type; end
  def team_drive_permission_type=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::Permission::TeamDrivePermissionDetail::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::PermissionList
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def kind; end
  def kind=(_arg0); end
  def next_page_token; end
  def next_page_token=(_arg0); end
  def permissions; end
  def permissions=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::PermissionList::Representation < ::Google::Apis::Core::JsonRepresentation
end

Google::Apis::DriveV3::REVISION = T.let(T.unsafe(nil), String)

class Google::Apis::DriveV3::Reply
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def action; end
  def action=(_arg0); end
  def author; end
  def author=(_arg0); end
  def content; end
  def content=(_arg0); end
  def created_time; end
  def created_time=(_arg0); end
  def deleted; end
  def deleted=(_arg0); end
  def deleted?; end
  def html_content; end
  def html_content=(_arg0); end
  def id; end
  def id=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def modified_time; end
  def modified_time=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::Reply::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::ReplyList
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def kind; end
  def kind=(_arg0); end
  def next_page_token; end
  def next_page_token=(_arg0); end
  def replies; end
  def replies=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::ReplyList::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::Revision
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def id; end
  def id=(_arg0); end
  def keep_forever; end
  def keep_forever=(_arg0); end
  def keep_forever?; end
  def kind; end
  def kind=(_arg0); end
  def last_modifying_user; end
  def last_modifying_user=(_arg0); end
  def md5_checksum; end
  def md5_checksum=(_arg0); end
  def mime_type; end
  def mime_type=(_arg0); end
  def modified_time; end
  def modified_time=(_arg0); end
  def original_filename; end
  def original_filename=(_arg0); end
  def publish_auto; end
  def publish_auto=(_arg0); end
  def publish_auto?; end
  def published; end
  def published=(_arg0); end
  def published?; end
  def published_outside_domain; end
  def published_outside_domain=(_arg0); end
  def published_outside_domain?; end
  def size; end
  def size=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::Revision::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::RevisionList
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def kind; end
  def kind=(_arg0); end
  def next_page_token; end
  def next_page_token=(_arg0); end
  def revisions; end
  def revisions=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::RevisionList::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::StartPageToken
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def kind; end
  def kind=(_arg0); end
  def start_page_token; end
  def start_page_token=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::StartPageToken::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::TeamDrive
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def background_image_file; end
  def background_image_file=(_arg0); end
  def background_image_link; end
  def background_image_link=(_arg0); end
  def capabilities; end
  def capabilities=(_arg0); end
  def color_rgb; end
  def color_rgb=(_arg0); end
  def created_time; end
  def created_time=(_arg0); end
  def id; end
  def id=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def name; end
  def name=(_arg0); end
  def theme_id; end
  def theme_id=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::TeamDrive::BackgroundImageFile
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def id; end
  def id=(_arg0); end
  def update!(**args); end
  def width; end
  def width=(_arg0); end
  def x_coordinate; end
  def x_coordinate=(_arg0); end
  def y_coordinate; end
  def y_coordinate=(_arg0); end
end

class Google::Apis::DriveV3::TeamDrive::BackgroundImageFile::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::TeamDrive::Capabilities
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def can_add_children; end
  def can_add_children=(_arg0); end
  def can_add_children?; end
  def can_change_team_drive_background; end
  def can_change_team_drive_background=(_arg0); end
  def can_change_team_drive_background?; end
  def can_comment; end
  def can_comment=(_arg0); end
  def can_comment?; end
  def can_copy; end
  def can_copy=(_arg0); end
  def can_copy?; end
  def can_delete_team_drive; end
  def can_delete_team_drive=(_arg0); end
  def can_delete_team_drive?; end
  def can_download; end
  def can_download=(_arg0); end
  def can_download?; end
  def can_edit; end
  def can_edit=(_arg0); end
  def can_edit?; end
  def can_list_children; end
  def can_list_children=(_arg0); end
  def can_list_children?; end
  def can_manage_members; end
  def can_manage_members=(_arg0); end
  def can_manage_members?; end
  def can_read_revisions; end
  def can_read_revisions=(_arg0); end
  def can_read_revisions?; end
  def can_remove_children; end
  def can_remove_children=(_arg0); end
  def can_remove_children?; end
  def can_rename; end
  def can_rename=(_arg0); end
  def can_rename?; end
  def can_rename_team_drive; end
  def can_rename_team_drive=(_arg0); end
  def can_rename_team_drive?; end
  def can_share; end
  def can_share=(_arg0); end
  def can_share?; end
  def update!(**args); end
end

class Google::Apis::DriveV3::TeamDrive::Capabilities::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::TeamDrive::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::TeamDriveList
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def kind; end
  def kind=(_arg0); end
  def next_page_token; end
  def next_page_token=(_arg0); end
  def team_drives; end
  def team_drives=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::TeamDriveList::Representation < ::Google::Apis::Core::JsonRepresentation
end

class Google::Apis::DriveV3::User
  include(::Google::Apis::Core::Hashable)
  include(::Google::Apis::Core::JsonObjectSupport)
  extend(::Google::Apis::Core::JsonObjectSupport::ClassMethods)

  def initialize(**args); end

  def display_name; end
  def display_name=(_arg0); end
  def email_address; end
  def email_address=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def me; end
  def me=(_arg0); end
  def me?; end
  def permission_id; end
  def permission_id=(_arg0); end
  def photo_link; end
  def photo_link=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::User::Representation < ::Google::Apis::Core::JsonRepresentation
end

Google::Apis::DriveV3::VERSION = T.let(T.unsafe(nil), String)

class Google::Apis::Error < ::StandardError
  def initialize(err, status_code: T.unsafe(nil), header: T.unsafe(nil), body: T.unsafe(nil)); end

  def backtrace; end
  def body; end
  def header; end
  def status_code; end
end

Google::Apis::OS_VERSION = T.let(T.unsafe(nil), String)

class Google::Apis::ProjectNotLinkedError < ::Google::Apis::Error
end

Google::Apis::ROOT = T.let(T.unsafe(nil), String)

class Google::Apis::RateLimitError < ::Google::Apis::Error
end

class Google::Apis::RedirectError < ::Google::Apis::Error
end

class Google::Apis::RequestOptions < ::Struct
  def api_format_version; end
  def api_format_version=(_); end
  def authorization; end
  def authorization=(_); end
  def header; end
  def header=(_); end
  def merge(options); end
  def normalize_unicode; end
  def normalize_unicode=(_); end
  def retries; end
  def retries=(_); end
  def skip_deserialization; end
  def skip_deserialization=(_); end
  def skip_serialization; end
  def skip_serialization=(_); end

  class << self
    def [](*_arg0); end
    def default; end
    def inspect; end
    def members; end
    def new(*_arg0); end
  end
end

class Google::Apis::ServerError < ::Google::Apis::Error
end

class Google::Apis::TransmissionError < ::Google::Apis::Error
end

Google::Apis::VERSION = T.let(T.unsafe(nil), String)
