# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `google-apis-drive_v3` gem.
# Please instead update this file by running `bin/tapioca gem google-apis-drive_v3`.

# typed: true

module Google; end

module Google::Apis
  class << self
    def default_logger; end
    def logger; end
    def logger=(_arg0); end
    def rails_logger; end
  end
end

module Google::Apis::DriveV3; end
Google::Apis::DriveV3::AUTH_DRIVE = T.let(T.unsafe(nil), String)
Google::Apis::DriveV3::AUTH_DRIVE_APPDATA = T.let(T.unsafe(nil), String)
Google::Apis::DriveV3::AUTH_DRIVE_FILE = T.let(T.unsafe(nil), String)
Google::Apis::DriveV3::AUTH_DRIVE_METADATA = T.let(T.unsafe(nil), String)
Google::Apis::DriveV3::AUTH_DRIVE_METADATA_READONLY = T.let(T.unsafe(nil), String)
Google::Apis::DriveV3::AUTH_DRIVE_PHOTOS_READONLY = T.let(T.unsafe(nil), String)
Google::Apis::DriveV3::AUTH_DRIVE_READONLY = T.let(T.unsafe(nil), String)
Google::Apis::DriveV3::AUTH_DRIVE_SCRIPTS = T.let(T.unsafe(nil), String)

class Google::Apis::DriveV3::About
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def app_installed; end
  def app_installed=(_arg0); end
  def app_installed?; end
  def can_create_drives; end
  def can_create_drives=(_arg0); end
  def can_create_drives?; end
  def can_create_team_drives; end
  def can_create_team_drives=(_arg0); end
  def can_create_team_drives?; end
  def drive_themes; end
  def drive_themes=(_arg0); end
  def export_formats; end
  def export_formats=(_arg0); end
  def folder_color_palette; end
  def folder_color_palette=(_arg0); end
  def import_formats; end
  def import_formats=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def max_import_sizes; end
  def max_import_sizes=(_arg0); end
  def max_upload_size; end
  def max_upload_size=(_arg0); end
  def storage_quota; end
  def storage_quota=(_arg0); end
  def team_drive_themes; end
  def team_drive_themes=(_arg0); end
  def update!(**args); end
  def user; end
  def user=(_arg0); end
end

class Google::Apis::DriveV3::About::DriveTheme
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def background_image_link; end
  def background_image_link=(_arg0); end
  def color_rgb; end
  def color_rgb=(_arg0); end
  def id; end
  def id=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::About::DriveTheme::Representation < ::Google::Apis::Core::JsonRepresentation; end
class Google::Apis::DriveV3::About::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::About::StorageQuota
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def limit; end
  def limit=(_arg0); end
  def update!(**args); end
  def usage; end
  def usage=(_arg0); end
  def usage_in_drive; end
  def usage_in_drive=(_arg0); end
  def usage_in_drive_trash; end
  def usage_in_drive_trash=(_arg0); end
end

class Google::Apis::DriveV3::About::StorageQuota::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::About::TeamDriveTheme
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def background_image_link; end
  def background_image_link=(_arg0); end
  def color_rgb; end
  def color_rgb=(_arg0); end
  def id; end
  def id=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::About::TeamDriveTheme::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::Change
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def change_type; end
  def change_type=(_arg0); end
  def drive; end
  def drive=(_arg0); end
  def drive_id; end
  def drive_id=(_arg0); end
  def file; end
  def file=(_arg0); end
  def file_id; end
  def file_id=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def removed; end
  def removed=(_arg0); end
  def removed?; end
  def team_drive; end
  def team_drive=(_arg0); end
  def team_drive_id; end
  def team_drive_id=(_arg0); end
  def time; end
  def time=(_arg0); end
  def type; end
  def type=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::Change::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::ChangeList
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def changes; end
  def changes=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def new_start_page_token; end
  def new_start_page_token=(_arg0); end
  def next_page_token; end
  def next_page_token=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::ChangeList::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::Channel
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def address; end
  def address=(_arg0); end
  def expiration; end
  def expiration=(_arg0); end
  def id; end
  def id=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def params; end
  def params=(_arg0); end
  def payload; end
  def payload=(_arg0); end
  def payload?; end
  def resource_id; end
  def resource_id=(_arg0); end
  def resource_uri; end
  def resource_uri=(_arg0); end
  def token; end
  def token=(_arg0); end
  def type; end
  def type=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::Channel::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::Comment
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def anchor; end
  def anchor=(_arg0); end
  def author; end
  def author=(_arg0); end
  def content; end
  def content=(_arg0); end
  def created_time; end
  def created_time=(_arg0); end
  def deleted; end
  def deleted=(_arg0); end
  def deleted?; end
  def html_content; end
  def html_content=(_arg0); end
  def id; end
  def id=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def modified_time; end
  def modified_time=(_arg0); end
  def quoted_file_content; end
  def quoted_file_content=(_arg0); end
  def replies; end
  def replies=(_arg0); end
  def resolved; end
  def resolved=(_arg0); end
  def resolved?; end
  def update!(**args); end
end

class Google::Apis::DriveV3::Comment::QuotedFileContent
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def mime_type; end
  def mime_type=(_arg0); end
  def update!(**args); end
  def value; end
  def value=(_arg0); end
end

class Google::Apis::DriveV3::Comment::QuotedFileContent::Representation < ::Google::Apis::Core::JsonRepresentation; end
class Google::Apis::DriveV3::Comment::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::CommentList
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def comments; end
  def comments=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def next_page_token; end
  def next_page_token=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::CommentList::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::ContentRestriction
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def read_only; end
  def read_only=(_arg0); end
  def read_only?; end
  def reason; end
  def reason=(_arg0); end
  def restricting_user; end
  def restricting_user=(_arg0); end
  def restriction_time; end
  def restriction_time=(_arg0); end
  def type; end
  def type=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::ContentRestriction::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::Drive
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def background_image_file; end
  def background_image_file=(_arg0); end
  def background_image_link; end
  def background_image_link=(_arg0); end
  def capabilities; end
  def capabilities=(_arg0); end
  def color_rgb; end
  def color_rgb=(_arg0); end
  def created_time; end
  def created_time=(_arg0); end
  def hidden; end
  def hidden=(_arg0); end
  def hidden?; end
  def id; end
  def id=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def name; end
  def name=(_arg0); end
  def restrictions; end
  def restrictions=(_arg0); end
  def theme_id; end
  def theme_id=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::Drive::BackgroundImageFile
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def id; end
  def id=(_arg0); end
  def update!(**args); end
  def width; end
  def width=(_arg0); end
  def x_coordinate; end
  def x_coordinate=(_arg0); end
  def y_coordinate; end
  def y_coordinate=(_arg0); end
end

class Google::Apis::DriveV3::Drive::BackgroundImageFile::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::Drive::Capabilities
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def can_add_children; end
  def can_add_children=(_arg0); end
  def can_add_children?; end
  def can_change_copy_requires_writer_permission_restriction; end
  def can_change_copy_requires_writer_permission_restriction=(_arg0); end
  def can_change_copy_requires_writer_permission_restriction?; end
  def can_change_domain_users_only_restriction; end
  def can_change_domain_users_only_restriction=(_arg0); end
  def can_change_domain_users_only_restriction?; end
  def can_change_drive_background; end
  def can_change_drive_background=(_arg0); end
  def can_change_drive_background?; end
  def can_change_drive_members_only_restriction; end
  def can_change_drive_members_only_restriction=(_arg0); end
  def can_change_drive_members_only_restriction?; end
  def can_comment; end
  def can_comment=(_arg0); end
  def can_comment?; end
  def can_copy; end
  def can_copy=(_arg0); end
  def can_copy?; end
  def can_delete_children; end
  def can_delete_children=(_arg0); end
  def can_delete_children?; end
  def can_delete_drive; end
  def can_delete_drive=(_arg0); end
  def can_delete_drive?; end
  def can_download; end
  def can_download=(_arg0); end
  def can_download?; end
  def can_edit; end
  def can_edit=(_arg0); end
  def can_edit?; end
  def can_list_children; end
  def can_list_children=(_arg0); end
  def can_list_children?; end
  def can_manage_members; end
  def can_manage_members=(_arg0); end
  def can_manage_members?; end
  def can_read_revisions; end
  def can_read_revisions=(_arg0); end
  def can_read_revisions?; end
  def can_rename; end
  def can_rename=(_arg0); end
  def can_rename?; end
  def can_rename_drive; end
  def can_rename_drive=(_arg0); end
  def can_rename_drive?; end
  def can_share; end
  def can_share=(_arg0); end
  def can_share?; end
  def can_trash_children; end
  def can_trash_children=(_arg0); end
  def can_trash_children?; end
  def update!(**args); end
end

class Google::Apis::DriveV3::Drive::Capabilities::Representation < ::Google::Apis::Core::JsonRepresentation; end
class Google::Apis::DriveV3::Drive::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::Drive::Restrictions
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def admin_managed_restrictions; end
  def admin_managed_restrictions=(_arg0); end
  def admin_managed_restrictions?; end
  def copy_requires_writer_permission; end
  def copy_requires_writer_permission=(_arg0); end
  def copy_requires_writer_permission?; end
  def domain_users_only; end
  def domain_users_only=(_arg0); end
  def domain_users_only?; end
  def drive_members_only; end
  def drive_members_only=(_arg0); end
  def drive_members_only?; end
  def update!(**args); end
end

class Google::Apis::DriveV3::Drive::Restrictions::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::DriveList
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def drives; end
  def drives=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def next_page_token; end
  def next_page_token=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::DriveList::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::DriveService < ::Google::Apis::Core::BaseService
  def initialize; end

  def copy_file(file_id, file_object = T.unsafe(nil), enforce_single_parent: T.unsafe(nil), ignore_default_visibility: T.unsafe(nil), include_permissions_for_view: T.unsafe(nil), keep_revision_forever: T.unsafe(nil), ocr_language: T.unsafe(nil), supports_all_drives: T.unsafe(nil), supports_team_drives: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def create_comment(file_id, comment_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def create_drive(request_id, drive_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def create_file(file_object = T.unsafe(nil), enforce_single_parent: T.unsafe(nil), ignore_default_visibility: T.unsafe(nil), include_permissions_for_view: T.unsafe(nil), keep_revision_forever: T.unsafe(nil), ocr_language: T.unsafe(nil), supports_all_drives: T.unsafe(nil), supports_team_drives: T.unsafe(nil), use_content_as_indexable_text: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), upload_source: T.unsafe(nil), content_type: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def create_permission(file_id, permission_object = T.unsafe(nil), email_message: T.unsafe(nil), enforce_single_parent: T.unsafe(nil), move_to_new_owners_root: T.unsafe(nil), send_notification_email: T.unsafe(nil), supports_all_drives: T.unsafe(nil), supports_team_drives: T.unsafe(nil), transfer_ownership: T.unsafe(nil), use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def create_reply(file_id, comment_id, reply_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def create_teamdrive(request_id, team_drive_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def delete_comment(file_id, comment_id, fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def delete_drive(drive_id, fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def delete_file(file_id, enforce_single_parent: T.unsafe(nil), supports_all_drives: T.unsafe(nil), supports_team_drives: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def delete_permission(file_id, permission_id, supports_all_drives: T.unsafe(nil), supports_team_drives: T.unsafe(nil), use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def delete_reply(file_id, comment_id, reply_id, fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def delete_revision(file_id, revision_id, fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def delete_teamdrive(team_drive_id, fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def empty_file_trash(enforce_single_parent: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def export_file(file_id, mime_type, fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), download_dest: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def generate_file_ids(count: T.unsafe(nil), space: T.unsafe(nil), type: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_about(fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_changes_start_page_token(drive_id: T.unsafe(nil), supports_all_drives: T.unsafe(nil), supports_team_drives: T.unsafe(nil), team_drive_id: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_comment(file_id, comment_id, include_deleted: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_drive(drive_id, use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_file(file_id, acknowledge_abuse: T.unsafe(nil), include_permissions_for_view: T.unsafe(nil), supports_all_drives: T.unsafe(nil), supports_team_drives: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), download_dest: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_permission(file_id, permission_id, supports_all_drives: T.unsafe(nil), supports_team_drives: T.unsafe(nil), use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_reply(file_id, comment_id, reply_id, include_deleted: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_revision(file_id, revision_id, acknowledge_abuse: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), download_dest: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def get_teamdrive(team_drive_id, use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def hide_drive(drive_id, fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def key; end
  def key=(_arg0); end
  def list_changes(page_token, drive_id: T.unsafe(nil), include_corpus_removals: T.unsafe(nil), include_items_from_all_drives: T.unsafe(nil), include_permissions_for_view: T.unsafe(nil), include_removed: T.unsafe(nil), include_team_drive_items: T.unsafe(nil), page_size: T.unsafe(nil), restrict_to_my_drive: T.unsafe(nil), spaces: T.unsafe(nil), supports_all_drives: T.unsafe(nil), supports_team_drives: T.unsafe(nil), team_drive_id: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def list_comments(file_id, include_deleted: T.unsafe(nil), page_size: T.unsafe(nil), page_token: T.unsafe(nil), start_modified_time: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def list_drives(page_size: T.unsafe(nil), page_token: T.unsafe(nil), q: T.unsafe(nil), use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def list_files(corpora: T.unsafe(nil), corpus: T.unsafe(nil), drive_id: T.unsafe(nil), include_items_from_all_drives: T.unsafe(nil), include_permissions_for_view: T.unsafe(nil), include_team_drive_items: T.unsafe(nil), order_by: T.unsafe(nil), page_size: T.unsafe(nil), page_token: T.unsafe(nil), q: T.unsafe(nil), spaces: T.unsafe(nil), supports_all_drives: T.unsafe(nil), supports_team_drives: T.unsafe(nil), team_drive_id: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def list_permissions(file_id, include_permissions_for_view: T.unsafe(nil), page_size: T.unsafe(nil), page_token: T.unsafe(nil), supports_all_drives: T.unsafe(nil), supports_team_drives: T.unsafe(nil), use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def list_replies(file_id, comment_id, include_deleted: T.unsafe(nil), page_size: T.unsafe(nil), page_token: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def list_revisions(file_id, page_size: T.unsafe(nil), page_token: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def list_teamdrives(page_size: T.unsafe(nil), page_token: T.unsafe(nil), q: T.unsafe(nil), use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def quota_user; end
  def quota_user=(_arg0); end
  def stop_channel(channel_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def unhide_drive(drive_id, fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def update_comment(file_id, comment_id, comment_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def update_drive(drive_id, drive_object = T.unsafe(nil), use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def update_file(file_id, file_object = T.unsafe(nil), add_parents: T.unsafe(nil), enforce_single_parent: T.unsafe(nil), include_permissions_for_view: T.unsafe(nil), keep_revision_forever: T.unsafe(nil), ocr_language: T.unsafe(nil), remove_parents: T.unsafe(nil), supports_all_drives: T.unsafe(nil), supports_team_drives: T.unsafe(nil), use_content_as_indexable_text: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), upload_source: T.unsafe(nil), content_type: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def update_permission(file_id, permission_id, permission_object = T.unsafe(nil), remove_expiration: T.unsafe(nil), supports_all_drives: T.unsafe(nil), supports_team_drives: T.unsafe(nil), transfer_ownership: T.unsafe(nil), use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def update_reply(file_id, comment_id, reply_id, reply_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def update_revision(file_id, revision_id, revision_object = T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def update_teamdrive(team_drive_id, team_drive_object = T.unsafe(nil), use_domain_admin_access: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def user_ip; end
  def user_ip=(_arg0); end
  def watch_change(page_token, channel_object = T.unsafe(nil), drive_id: T.unsafe(nil), include_corpus_removals: T.unsafe(nil), include_items_from_all_drives: T.unsafe(nil), include_permissions_for_view: T.unsafe(nil), include_removed: T.unsafe(nil), include_team_drive_items: T.unsafe(nil), page_size: T.unsafe(nil), restrict_to_my_drive: T.unsafe(nil), spaces: T.unsafe(nil), supports_all_drives: T.unsafe(nil), supports_team_drives: T.unsafe(nil), team_drive_id: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), options: T.unsafe(nil), &block); end
  def watch_file(file_id, channel_object = T.unsafe(nil), acknowledge_abuse: T.unsafe(nil), include_permissions_for_view: T.unsafe(nil), supports_all_drives: T.unsafe(nil), supports_team_drives: T.unsafe(nil), fields: T.unsafe(nil), quota_user: T.unsafe(nil), user_ip: T.unsafe(nil), download_dest: T.unsafe(nil), options: T.unsafe(nil), &block); end

  protected

  def apply_command_defaults(command); end
end

class Google::Apis::DriveV3::File
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def app_properties; end
  def app_properties=(_arg0); end
  def capabilities; end
  def capabilities=(_arg0); end
  def content_hints; end
  def content_hints=(_arg0); end
  def content_restrictions; end
  def content_restrictions=(_arg0); end
  def copy_requires_writer_permission; end
  def copy_requires_writer_permission=(_arg0); end
  def copy_requires_writer_permission?; end
  def created_time; end
  def created_time=(_arg0); end
  def description; end
  def description=(_arg0); end
  def drive_id; end
  def drive_id=(_arg0); end
  def explicitly_trashed; end
  def explicitly_trashed=(_arg0); end
  def explicitly_trashed?; end
  def export_links; end
  def export_links=(_arg0); end
  def file_extension; end
  def file_extension=(_arg0); end
  def folder_color_rgb; end
  def folder_color_rgb=(_arg0); end
  def full_file_extension; end
  def full_file_extension=(_arg0); end
  def has_augmented_permissions; end
  def has_augmented_permissions=(_arg0); end
  def has_augmented_permissions?; end
  def has_thumbnail; end
  def has_thumbnail=(_arg0); end
  def has_thumbnail?; end
  def head_revision_id; end
  def head_revision_id=(_arg0); end
  def icon_link; end
  def icon_link=(_arg0); end
  def id; end
  def id=(_arg0); end
  def image_media_metadata; end
  def image_media_metadata=(_arg0); end
  def is_app_authorized; end
  def is_app_authorized=(_arg0); end
  def is_app_authorized?; end
  def kind; end
  def kind=(_arg0); end
  def last_modifying_user; end
  def last_modifying_user=(_arg0); end
  def link_share_metadata; end
  def link_share_metadata=(_arg0); end
  def md5_checksum; end
  def md5_checksum=(_arg0); end
  def mime_type; end
  def mime_type=(_arg0); end
  def modified_by_me; end
  def modified_by_me=(_arg0); end
  def modified_by_me?; end
  def modified_by_me_time; end
  def modified_by_me_time=(_arg0); end
  def modified_time; end
  def modified_time=(_arg0); end
  def name; end
  def name=(_arg0); end
  def original_filename; end
  def original_filename=(_arg0); end
  def owned_by_me; end
  def owned_by_me=(_arg0); end
  def owned_by_me?; end
  def owners; end
  def owners=(_arg0); end
  def parents; end
  def parents=(_arg0); end
  def permission_ids; end
  def permission_ids=(_arg0); end
  def permissions; end
  def permissions=(_arg0); end
  def properties; end
  def properties=(_arg0); end
  def quota_bytes_used; end
  def quota_bytes_used=(_arg0); end
  def resource_key; end
  def resource_key=(_arg0); end
  def shared; end
  def shared=(_arg0); end
  def shared?; end
  def shared_with_me_time; end
  def shared_with_me_time=(_arg0); end
  def sharing_user; end
  def sharing_user=(_arg0); end
  def shortcut_details; end
  def shortcut_details=(_arg0); end
  def size; end
  def size=(_arg0); end
  def spaces; end
  def spaces=(_arg0); end
  def starred; end
  def starred=(_arg0); end
  def starred?; end
  def team_drive_id; end
  def team_drive_id=(_arg0); end
  def thumbnail_link; end
  def thumbnail_link=(_arg0); end
  def thumbnail_version; end
  def thumbnail_version=(_arg0); end
  def trashed; end
  def trashed=(_arg0); end
  def trashed?; end
  def trashed_time; end
  def trashed_time=(_arg0); end
  def trashing_user; end
  def trashing_user=(_arg0); end
  def update!(**args); end
  def version; end
  def version=(_arg0); end
  def video_media_metadata; end
  def video_media_metadata=(_arg0); end
  def viewed_by_me; end
  def viewed_by_me=(_arg0); end
  def viewed_by_me?; end
  def viewed_by_me_time; end
  def viewed_by_me_time=(_arg0); end
  def viewers_can_copy_content; end
  def viewers_can_copy_content=(_arg0); end
  def viewers_can_copy_content?; end
  def web_content_link; end
  def web_content_link=(_arg0); end
  def web_view_link; end
  def web_view_link=(_arg0); end
  def writers_can_share; end
  def writers_can_share=(_arg0); end
  def writers_can_share?; end
end

class Google::Apis::DriveV3::File::Capabilities
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def can_add_children; end
  def can_add_children=(_arg0); end
  def can_add_children?; end
  def can_add_folder_from_another_drive; end
  def can_add_folder_from_another_drive=(_arg0); end
  def can_add_folder_from_another_drive?; end
  def can_add_my_drive_parent; end
  def can_add_my_drive_parent=(_arg0); end
  def can_add_my_drive_parent?; end
  def can_change_copy_requires_writer_permission; end
  def can_change_copy_requires_writer_permission=(_arg0); end
  def can_change_copy_requires_writer_permission?; end
  def can_change_security_update_enabled; end
  def can_change_security_update_enabled=(_arg0); end
  def can_change_security_update_enabled?; end
  def can_change_viewers_can_copy_content; end
  def can_change_viewers_can_copy_content=(_arg0); end
  def can_change_viewers_can_copy_content?; end
  def can_comment; end
  def can_comment=(_arg0); end
  def can_comment?; end
  def can_copy; end
  def can_copy=(_arg0); end
  def can_copy?; end
  def can_delete; end
  def can_delete=(_arg0); end
  def can_delete?; end
  def can_delete_children; end
  def can_delete_children=(_arg0); end
  def can_delete_children?; end
  def can_download; end
  def can_download=(_arg0); end
  def can_download?; end
  def can_edit; end
  def can_edit=(_arg0); end
  def can_edit?; end
  def can_list_children; end
  def can_list_children=(_arg0); end
  def can_list_children?; end
  def can_modify_content; end
  def can_modify_content=(_arg0); end
  def can_modify_content?; end
  def can_modify_content_restriction; end
  def can_modify_content_restriction=(_arg0); end
  def can_modify_content_restriction?; end
  def can_move_children_out_of_drive; end
  def can_move_children_out_of_drive=(_arg0); end
  def can_move_children_out_of_drive?; end
  def can_move_children_out_of_team_drive; end
  def can_move_children_out_of_team_drive=(_arg0); end
  def can_move_children_out_of_team_drive?; end
  def can_move_children_within_drive; end
  def can_move_children_within_drive=(_arg0); end
  def can_move_children_within_drive?; end
  def can_move_children_within_team_drive; end
  def can_move_children_within_team_drive=(_arg0); end
  def can_move_children_within_team_drive?; end
  def can_move_item_into_team_drive; end
  def can_move_item_into_team_drive=(_arg0); end
  def can_move_item_into_team_drive?; end
  def can_move_item_out_of_drive; end
  def can_move_item_out_of_drive=(_arg0); end
  def can_move_item_out_of_drive?; end
  def can_move_item_out_of_team_drive; end
  def can_move_item_out_of_team_drive=(_arg0); end
  def can_move_item_out_of_team_drive?; end
  def can_move_item_within_drive; end
  def can_move_item_within_drive=(_arg0); end
  def can_move_item_within_drive?; end
  def can_move_item_within_team_drive; end
  def can_move_item_within_team_drive=(_arg0); end
  def can_move_item_within_team_drive?; end
  def can_move_team_drive_item; end
  def can_move_team_drive_item=(_arg0); end
  def can_move_team_drive_item?; end
  def can_read_drive; end
  def can_read_drive=(_arg0); end
  def can_read_drive?; end
  def can_read_revisions; end
  def can_read_revisions=(_arg0); end
  def can_read_revisions?; end
  def can_read_team_drive; end
  def can_read_team_drive=(_arg0); end
  def can_read_team_drive?; end
  def can_remove_children; end
  def can_remove_children=(_arg0); end
  def can_remove_children?; end
  def can_remove_my_drive_parent; end
  def can_remove_my_drive_parent=(_arg0); end
  def can_remove_my_drive_parent?; end
  def can_rename; end
  def can_rename=(_arg0); end
  def can_rename?; end
  def can_share; end
  def can_share=(_arg0); end
  def can_share?; end
  def can_trash; end
  def can_trash=(_arg0); end
  def can_trash?; end
  def can_trash_children; end
  def can_trash_children=(_arg0); end
  def can_trash_children?; end
  def can_untrash; end
  def can_untrash=(_arg0); end
  def can_untrash?; end
  def update!(**args); end
end

class Google::Apis::DriveV3::File::Capabilities::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::File::ContentHints
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def indexable_text; end
  def indexable_text=(_arg0); end
  def thumbnail; end
  def thumbnail=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::File::ContentHints::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::File::ContentHints::Thumbnail
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def image; end
  def image=(_arg0); end
  def mime_type; end
  def mime_type=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::File::ContentHints::Thumbnail::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::File::ImageMediaMetadata
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def aperture; end
  def aperture=(_arg0); end
  def camera_make; end
  def camera_make=(_arg0); end
  def camera_model; end
  def camera_model=(_arg0); end
  def color_space; end
  def color_space=(_arg0); end
  def exposure_bias; end
  def exposure_bias=(_arg0); end
  def exposure_mode; end
  def exposure_mode=(_arg0); end
  def exposure_time; end
  def exposure_time=(_arg0); end
  def flash_used; end
  def flash_used=(_arg0); end
  def flash_used?; end
  def focal_length; end
  def focal_length=(_arg0); end
  def height; end
  def height=(_arg0); end
  def iso_speed; end
  def iso_speed=(_arg0); end
  def lens; end
  def lens=(_arg0); end
  def location; end
  def location=(_arg0); end
  def max_aperture_value; end
  def max_aperture_value=(_arg0); end
  def metering_mode; end
  def metering_mode=(_arg0); end
  def rotation; end
  def rotation=(_arg0); end
  def sensor; end
  def sensor=(_arg0); end
  def subject_distance; end
  def subject_distance=(_arg0); end
  def time; end
  def time=(_arg0); end
  def update!(**args); end
  def white_balance; end
  def white_balance=(_arg0); end
  def width; end
  def width=(_arg0); end
end

class Google::Apis::DriveV3::File::ImageMediaMetadata::Location
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def altitude; end
  def altitude=(_arg0); end
  def latitude; end
  def latitude=(_arg0); end
  def longitude; end
  def longitude=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::File::ImageMediaMetadata::Location::Representation < ::Google::Apis::Core::JsonRepresentation; end
class Google::Apis::DriveV3::File::ImageMediaMetadata::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::File::LinkShareMetadata
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def security_update_eligible; end
  def security_update_eligible=(_arg0); end
  def security_update_eligible?; end
  def security_update_enabled; end
  def security_update_enabled=(_arg0); end
  def security_update_enabled?; end
  def update!(**args); end
end

class Google::Apis::DriveV3::File::LinkShareMetadata::Representation < ::Google::Apis::Core::JsonRepresentation; end
class Google::Apis::DriveV3::File::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::File::ShortcutDetails
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def target_id; end
  def target_id=(_arg0); end
  def target_mime_type; end
  def target_mime_type=(_arg0); end
  def target_resource_key; end
  def target_resource_key=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::File::ShortcutDetails::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::File::VideoMediaMetadata
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def duration_millis; end
  def duration_millis=(_arg0); end
  def height; end
  def height=(_arg0); end
  def update!(**args); end
  def width; end
  def width=(_arg0); end
end

class Google::Apis::DriveV3::File::VideoMediaMetadata::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::FileList
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def files; end
  def files=(_arg0); end
  def incomplete_search; end
  def incomplete_search=(_arg0); end
  def incomplete_search?; end
  def kind; end
  def kind=(_arg0); end
  def next_page_token; end
  def next_page_token=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::FileList::Representation < ::Google::Apis::Core::JsonRepresentation; end
Google::Apis::DriveV3::GEM_VERSION = T.let(T.unsafe(nil), String)
Google::Apis::DriveV3::GENERATOR_VERSION = T.let(T.unsafe(nil), String)

class Google::Apis::DriveV3::GeneratedIds
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def ids; end
  def ids=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def space; end
  def space=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::GeneratedIds::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::Permission
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def allow_file_discovery; end
  def allow_file_discovery=(_arg0); end
  def allow_file_discovery?; end
  def deleted; end
  def deleted=(_arg0); end
  def deleted?; end
  def display_name; end
  def display_name=(_arg0); end
  def domain; end
  def domain=(_arg0); end
  def email_address; end
  def email_address=(_arg0); end
  def expiration_time; end
  def expiration_time=(_arg0); end
  def id; end
  def id=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def permission_details; end
  def permission_details=(_arg0); end
  def photo_link; end
  def photo_link=(_arg0); end
  def role; end
  def role=(_arg0); end
  def team_drive_permission_details; end
  def team_drive_permission_details=(_arg0); end
  def type; end
  def type=(_arg0); end
  def update!(**args); end
  def view; end
  def view=(_arg0); end
end

class Google::Apis::DriveV3::Permission::PermissionDetail
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def inherited; end
  def inherited=(_arg0); end
  def inherited?; end
  def inherited_from; end
  def inherited_from=(_arg0); end
  def permission_type; end
  def permission_type=(_arg0); end
  def role; end
  def role=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::Permission::PermissionDetail::Representation < ::Google::Apis::Core::JsonRepresentation; end
class Google::Apis::DriveV3::Permission::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::Permission::TeamDrivePermissionDetail
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def inherited; end
  def inherited=(_arg0); end
  def inherited?; end
  def inherited_from; end
  def inherited_from=(_arg0); end
  def role; end
  def role=(_arg0); end
  def team_drive_permission_type; end
  def team_drive_permission_type=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::Permission::TeamDrivePermissionDetail::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::PermissionList
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def kind; end
  def kind=(_arg0); end
  def next_page_token; end
  def next_page_token=(_arg0); end
  def permissions; end
  def permissions=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::PermissionList::Representation < ::Google::Apis::Core::JsonRepresentation; end
Google::Apis::DriveV3::REVISION = T.let(T.unsafe(nil), String)

class Google::Apis::DriveV3::Reply
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def action; end
  def action=(_arg0); end
  def author; end
  def author=(_arg0); end
  def content; end
  def content=(_arg0); end
  def created_time; end
  def created_time=(_arg0); end
  def deleted; end
  def deleted=(_arg0); end
  def deleted?; end
  def html_content; end
  def html_content=(_arg0); end
  def id; end
  def id=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def modified_time; end
  def modified_time=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::Reply::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::ReplyList
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def kind; end
  def kind=(_arg0); end
  def next_page_token; end
  def next_page_token=(_arg0); end
  def replies; end
  def replies=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::ReplyList::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::Revision
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def export_links; end
  def export_links=(_arg0); end
  def id; end
  def id=(_arg0); end
  def keep_forever; end
  def keep_forever=(_arg0); end
  def keep_forever?; end
  def kind; end
  def kind=(_arg0); end
  def last_modifying_user; end
  def last_modifying_user=(_arg0); end
  def md5_checksum; end
  def md5_checksum=(_arg0); end
  def mime_type; end
  def mime_type=(_arg0); end
  def modified_time; end
  def modified_time=(_arg0); end
  def original_filename; end
  def original_filename=(_arg0); end
  def publish_auto; end
  def publish_auto=(_arg0); end
  def publish_auto?; end
  def published; end
  def published=(_arg0); end
  def published?; end
  def published_link; end
  def published_link=(_arg0); end
  def published_outside_domain; end
  def published_outside_domain=(_arg0); end
  def published_outside_domain?; end
  def size; end
  def size=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::Revision::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::RevisionList
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def kind; end
  def kind=(_arg0); end
  def next_page_token; end
  def next_page_token=(_arg0); end
  def revisions; end
  def revisions=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::RevisionList::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::StartPageToken
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def kind; end
  def kind=(_arg0); end
  def start_page_token; end
  def start_page_token=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::StartPageToken::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::TeamDrive
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def background_image_file; end
  def background_image_file=(_arg0); end
  def background_image_link; end
  def background_image_link=(_arg0); end
  def capabilities; end
  def capabilities=(_arg0); end
  def color_rgb; end
  def color_rgb=(_arg0); end
  def created_time; end
  def created_time=(_arg0); end
  def id; end
  def id=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def name; end
  def name=(_arg0); end
  def restrictions; end
  def restrictions=(_arg0); end
  def theme_id; end
  def theme_id=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::TeamDrive::BackgroundImageFile
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def id; end
  def id=(_arg0); end
  def update!(**args); end
  def width; end
  def width=(_arg0); end
  def x_coordinate; end
  def x_coordinate=(_arg0); end
  def y_coordinate; end
  def y_coordinate=(_arg0); end
end

class Google::Apis::DriveV3::TeamDrive::BackgroundImageFile::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::TeamDrive::Capabilities
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def can_add_children; end
  def can_add_children=(_arg0); end
  def can_add_children?; end
  def can_change_copy_requires_writer_permission_restriction; end
  def can_change_copy_requires_writer_permission_restriction=(_arg0); end
  def can_change_copy_requires_writer_permission_restriction?; end
  def can_change_domain_users_only_restriction; end
  def can_change_domain_users_only_restriction=(_arg0); end
  def can_change_domain_users_only_restriction?; end
  def can_change_team_drive_background; end
  def can_change_team_drive_background=(_arg0); end
  def can_change_team_drive_background?; end
  def can_change_team_members_only_restriction; end
  def can_change_team_members_only_restriction=(_arg0); end
  def can_change_team_members_only_restriction?; end
  def can_comment; end
  def can_comment=(_arg0); end
  def can_comment?; end
  def can_copy; end
  def can_copy=(_arg0); end
  def can_copy?; end
  def can_delete_children; end
  def can_delete_children=(_arg0); end
  def can_delete_children?; end
  def can_delete_team_drive; end
  def can_delete_team_drive=(_arg0); end
  def can_delete_team_drive?; end
  def can_download; end
  def can_download=(_arg0); end
  def can_download?; end
  def can_edit; end
  def can_edit=(_arg0); end
  def can_edit?; end
  def can_list_children; end
  def can_list_children=(_arg0); end
  def can_list_children?; end
  def can_manage_members; end
  def can_manage_members=(_arg0); end
  def can_manage_members?; end
  def can_read_revisions; end
  def can_read_revisions=(_arg0); end
  def can_read_revisions?; end
  def can_remove_children; end
  def can_remove_children=(_arg0); end
  def can_remove_children?; end
  def can_rename; end
  def can_rename=(_arg0); end
  def can_rename?; end
  def can_rename_team_drive; end
  def can_rename_team_drive=(_arg0); end
  def can_rename_team_drive?; end
  def can_share; end
  def can_share=(_arg0); end
  def can_share?; end
  def can_trash_children; end
  def can_trash_children=(_arg0); end
  def can_trash_children?; end
  def update!(**args); end
end

class Google::Apis::DriveV3::TeamDrive::Capabilities::Representation < ::Google::Apis::Core::JsonRepresentation; end
class Google::Apis::DriveV3::TeamDrive::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::TeamDrive::Restrictions
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def admin_managed_restrictions; end
  def admin_managed_restrictions=(_arg0); end
  def admin_managed_restrictions?; end
  def copy_requires_writer_permission; end
  def copy_requires_writer_permission=(_arg0); end
  def copy_requires_writer_permission?; end
  def domain_users_only; end
  def domain_users_only=(_arg0); end
  def domain_users_only?; end
  def team_members_only; end
  def team_members_only=(_arg0); end
  def team_members_only?; end
  def update!(**args); end
end

class Google::Apis::DriveV3::TeamDrive::Restrictions::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::TeamDriveList
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def kind; end
  def kind=(_arg0); end
  def next_page_token; end
  def next_page_token=(_arg0); end
  def team_drives; end
  def team_drives=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::TeamDriveList::Representation < ::Google::Apis::Core::JsonRepresentation; end

class Google::Apis::DriveV3::User
  include ::Google::Apis::Core::Hashable
  include ::Google::Apis::Core::JsonObjectSupport
  extend ::Google::Apis::Core::JsonObjectSupport::ClassMethods

  def initialize(**args); end

  def display_name; end
  def display_name=(_arg0); end
  def email_address; end
  def email_address=(_arg0); end
  def kind; end
  def kind=(_arg0); end
  def me; end
  def me=(_arg0); end
  def me?; end
  def permission_id; end
  def permission_id=(_arg0); end
  def photo_link; end
  def photo_link=(_arg0); end
  def update!(**args); end
end

class Google::Apis::DriveV3::User::Representation < ::Google::Apis::Core::JsonRepresentation; end
Google::Apis::DriveV3::VERSION = T.let(T.unsafe(nil), String)
Google::Apis::OS_VERSION = T.let(T.unsafe(nil), String)
Google::Apis::ROOT = T.let(T.unsafe(nil), String)
