# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `memoist` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module Memoist
  def all_memoized_structs; end
  def clear_structs; end
  def memoize(*method_names); end

  class << self
    def escape_punctuation(string); end
    def extended(extender); end
    def extract_reload!(method, args); end
    def memoist_eval(klass, *args, &block); end
    def memoized_ivar_for(method_name, identifier = T.unsafe(nil)); end
    def memoized_prefix(identifier = T.unsafe(nil)); end
    def unmemoized_method_for(method_name, identifier = T.unsafe(nil)); end
    def unmemoized_prefix(identifier = T.unsafe(nil)); end
  end
end

module Memoist::InstanceMethods
  def flush_cache(*method_names); end
  def memoize_all; end
  def memoized_structs(names); end
  def prime_cache(*method_names); end
  def unmemoize_all; end
end

class Memoist::MemoizedMethod < ::Struct
  def arity; end
  def arity=(_); end
  def ivar; end
  def ivar=(_); end
  def memoized_method; end
  def memoized_method=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def members; end
    def new(*_arg0); end
  end
end

Memoist::VERSION = T.let(T.unsafe(nil), String)
