# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `os` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

class OS
  def config; end

  class << self
    def app_config_path(name); end
    def bits; end
    def config; end
    def cpu_count; end
    def cygwin?; end
    def dev_null; end
    def doze?; end
    def freebsd?; end
    def host; end
    def host_cpu; end
    def host_os; end
    def hwprefs_available?; end
    def iron_ruby?; end
    def java?; end
    def jruby?; end
    def linux?; end
    def mac?; end
    def open_file_command; end
    def osx?; end
    def parse_os_release; end
    def posix?; end
    def report; end
    def rss_bytes; end
    def ruby_bin; end
    def windows?; end
    def x?; end
  end
end

class OS::Underlying
  class << self
    def bsd?; end
    def docker?; end
    def linux?; end
    def windows?; end
  end
end
