# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rexml` gem.
# Please instead update this file by running `bin/tapioca gem rexml`.

# typed: true

class Float < ::Numeric
  include ::JSON::Ext::Generator::GeneratorMethods::Float
end

class Symbol
  include ::Comparable
end
