# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `trailblazer-option` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module Trailblazer
  class << self
    def Option(value); end
  end
end

class Trailblazer::Option
  class << self
    def build(value); end
    def call!(value, *args, signal: T.unsafe(nil), keyword_arguments: T.unsafe(nil), **_arg4, &block); end
    def evaluate_callable(value, *args, **options, &block); end
    def evaluate_method(value, *args, exec_context: T.unsafe(nil), **options, &block); end
    def evaluate_proc(value, *args, signal: T.unsafe(nil), exec_context: T.unsafe(nil), **options); end
    def evaluator(value, *args, **options, &block); end
  end
end
