# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `uber` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module Uber
end

module Uber::Callable
end

module Uber::Delegates
  def delegates(model, *names); end
end

module Uber::InheritableAttr
  def inheritable_attr(name, options = T.unsafe(nil)); end

  class << self
    def inherit_for(klass, name, options = T.unsafe(nil)); end
  end
end

class Uber::InheritableAttr::Clone
  class << self
    def call(value, uncloneable = T.unsafe(nil)); end
    def uncloneable; end
  end
end

Uber::InheritableAttribute = Uber::InheritableAttr
