Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3

Metrics/MethodLength:   
  Max: 30

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: braces
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/NumericPredicate:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/RaiseArgs:
  Enabled: false
